-- require('plugins.lazy')
require('plugins.theme')
require('plugins.mason')
require('plugins.lualine')
require('plugins.fzf')
require('plugins.blink')
require('plugins.neotree')
require('plugins.autopairs')
require('plugins.gitsigns')
require('plugins.alpha')
require('plugins.which-key')
require('plugins.conform')
require('plugins.lint')
require('plugins.noice')
require('plugins.opencode')
-- require('plugins.snacks')
require('plugins.todo-comments')
require('plugins.trouble')
require('plugins.ts-comments')
