[colors]
# Фон самого окна (темно-синий, слегка прозрачный)
background=1e1e2eff

# Цвет обычного текста (светлый)
text=cdd6f4ff

# Цвет текста, который совпал с поисковым запросом
match=f38ba8ff

# Фон выделенного пункта меню
selection=585b70ff

# Текст выделенного пункта меню
selection-text=cdd6f4ff

# Цвет совпавших букв в выделенном пункте
selection-match=f38ba8ff

# Цвет рамки окна (фиолетовый border)
border=cba6f7ff
