[main]
term=foot
shell=fish
initial-window-size-chars=82x25
initial-window-mode=windowed
font=JetBrainsMono Nerd Font:size=16

[cursor]
style=block
blink=yes
unfocused-style=unchanged

[colors-dark]
# primary
background=1D212A
foreground=E3E3E3
# normal
regular0=1D212A
regular1=FC8993
regular2=89E19C
regular3=FBDF90
regular4=A7BDFB
regular5=D990CD
regular6=81D4EE
regular7=E3E3E3
# bright
bright0=585E74
bright1=FB9199
bright2=8DE19F
bright3=FFE28E
bright4=AFC3FB
bright5=DF95D3
bright6=81D4EE
bright7=E3E3E3

[key-bindings]
clipboard-copy=Control+c
clipboard-paste=Control+v Control+Shift+v

[text-bindings]
\x03=Control+Shift+c
